name: "lakehouse_dbt"
version: "0.0.0"
config-version: 2

profile: "lakehouse_dbt"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  lakehouse_dbt:
    +materialized: view
